config/routes.rb
GrantTracker::Application.routes.draw do
 
  root :to => 'pages#index'
  get '/dashboard' => 'pages#dashboard', as: 'dashboard'
  
  get '/new/user' => 'organizations#new_user', as: 'org_user'
  get '/new/grant' => 'grants#new', as: 'org_grant'
  get '/new/:id/task' => 'tasks#new', as: 'org_task'
  
  get '/edit' => 'organizations#edit', as: 'edit_org'
  
  get '/signup' => 'organizations#new', as: 'signup'
  get '/organizations/:id/new_user' => 'organizations#new_user', as: 'organization_user'
  post '/users' => 'organizations#create_user'
  
  root :to => 'users#index'
  
  resources :user_sessions
  resources :users
  resources :tasks
  resources :grants
  resources :organizations, path: 'organization'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/pages/_admin.html.erb
<p>ADMIN DASH</p>




<%= link_to "New Grant", new_grant_path %> | <%= link_to 'Edit', edit_org_path %>

app/views/pages/_admin1.html.erb
<h2>ADMIN DASH</h2>

<h3>All Users</h3>

<ul>
  <% @org.users.each do |user| %>
    <%= content_tag_for :li, user do %>
      <%= user.name %>
    <% end %>
  <% end %>
</ul>

<h3>All Tasks</h3>

 <ul>
   <% @org.tasks.each do |task| %>
     <%= content_tag_for :li, task do %>
       <%= link_to task.name, task_path(task.id) %>, Due: <%= if task.due then task.due.strftime("%m/%d/%Y") else "None" end %>
     <% end %>
   <% end %>
 </ul>
 
<h3>All Grants</h3>
 
 <ul>
   <% @org.grants.each do |grant| %>
     <%= content_tag_for :li, grant do %>
       <%= link_to grant.name, grant_path(grant.id) %> 
     <% end %>
   <% end %>
 </ul>


<%= link_to "Add New User to #{@org.name}", org_user_path %> <br />

<%= link_to "New Grant", new_grant_path %> | <%= link_to 'Edit', edit_org_path %>

app/views/pages/_admin_nav.html.erb
<ul class="admin-nav-ul">
  <li class="admin-nav-link"><%= link_to "New User", org_user_path %></li>
  <li class="admin-nav-link"><%= link_to "New Grant", new_grant_path %></li>
  <li class="admin-nav-link"><%= link_to 'All Users', users_path %></li>
  <li class="admin-nav-link"><%= link_to 'Edit', edit_org_path %></li>
</ul>

app/views/pages/_dash.html.erb
<p><b>Assigned Tasks:</b></p>

 <ul class='dash-ul'>
   <% @non_admin_tasks.each do |task| %>
     <%= content_tag_for :li, task, class: 'dash-li' do %>
       <%= link_to task.name, task_path(task.id), class: 'dash-link' %>
       <p class="task-due"><%= if task.due then task.due.strftime("%m/%d/%Y") else "None" end %></p>
     <% end %>
   <% end %>
 </ul>

app/views/pages/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Organization Name" %><br />
    <%= f.text_field :name %>
  </div>
  
    <%= f.fields_for :users do |d| %>
      
    
        <div class="field">
          <%= d.label :name, "Your Name" %><br />
          <%= d.text_field :name %>
        </div>
      
        <div class="field">
          <%= d.label :email %><br />
          <%= d.text_field :email %>
        </div>
      
        <div class="field">
          <%= d.label :password %><br />
          <%= d.password_field :password %>
        </div>
      
        <div class="field">
          <%= d.label :password_confirmation %><br />
          <%= d.password_field :password_confirmation %>
        </div>
      
    <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/dashboard.html.erb
<% if current_user.admin %>
  <%= render 'admin_nav' %> 
<% else %>
  <%= render 'dash' %>
<% end %>

<% if current_user.admin %>
  <%= render 'admin' %> 
<% end %>

app/views/pages/index.html.erb
<div id ="pages-index">
  <h1>Grant Tracker</h1>
  <hr/>
  

      <p>Your slogan here!</p>
<hr/>
<% if current_user %>
<% else %>
<a href="#"> Sign Up! </a>
<% end %>
</div>
<p id="pages-content"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<div id="pages-form"><%= render 'form' %></div>