config/routes.rb
GrantTracker::Application.routes.draw do
 
  root :to => 'pages#index'
  get '/dashboard' => 'pages#dashboard', as: 'dashboard'
  
  get '/new/user' => 'organizations#new_user', as: 'org_user'
  get '/new/grant' => 'grants#new', as: 'org_grant'
  get '/new/:id/task' => 'tasks#new', as: 'org_task'
  
  get '/edit' => 'organizations#edit', as: 'edit_org'
  
  get '/signup' => 'organizations#new', as: 'signup'
  get '/organizations/:id/new_user' => 'organizations#new_user', as: 'organization_user'
  post '/users' => 'organizations#create_user'
  
  root :to => 'users#index'
  
  resources :user_sessions
  resources :users
  resources :tasks
  resources :grants
  resources :organizations, path: 'organization'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/grant.rb
class Grant < ActiveRecord::Base
  attr_accessible :name, :private, :tasks_attributes, :uploads_attributes # :image
  
  has_many :tasks
  belongs_to :organization
  has_many :uploads
  
  validates :name, presence: true

  # mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :tasks
  accepts_nested_attributes_for :uploads
end

app/controllers/grants_controller.rb
class GrantsController < ApplicationController
  # GET /grants
  # GET /grants.json
  def index
    @grants = Grant.includes(:tasks).where(organization_id: current_user.organization_id)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grants }
    end
  end

  # GET /grants/1
  # GET /grants/1.json
  def show
    @grant = Grant.find(params[:id])
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grant }
    end
  end

  # GET /grants/new
  # GET /grants/new.json
  def new
    
    # Only allows admin to create new grants.
    if current_user.admin == true
      @grant = Grant.new
    
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @grant }
      end
    else
      respond_to do |format|
        format.html { redirect_to dashboard_path, alert: 'Must be admin to create grant.' }
        format.json { render json: @grant }
      end
    end
  end

  # GET /grants/1/edit
  def edit
    @grant = Grant.find(params[:id])
  end

  # POST /grants
  # POST /grants.json
  def create
    if current_user.admin == true
      @grant = Grant.new(params[:grant])
      @grant.update_attribute('organization_id', current_user.organization_id)
      
      respond_to do |format|
        if @grant.save
          format.html { redirect_to @grant, notice: 'Grant was successfully created.' }
          format.json { render json: @grant, status: :created, location: @grant }
        else
          format.html { render action: "new" }
          format.json { render json: @grant.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /grants/1
  # PUT /grants/1.json
  def update
    @grant = Grant.find(params[:id])

    respond_to do |format|
      if @grant.update_attributes(params[:grant])
        format.html { redirect_to grant_path, notice: 'Grant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grants/1
  # DELETE /grants/1.json
  def destroy
    @grant = Grant.find(params[:id])
    @grant.destroy

    respond_to do |format|
      format.html { redirect_to grants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/views/grants/_form.html.erb
<%= form_for(@grant) do |f| %>
  <% if @grant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grant.errors.count, "error") %> prohibited this grant from being saved:</h2>

      <ul>
      <% @grant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label "Private - Can only be viewed by other admins" %><br />
    <%= f.check_box :private %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grants/edit.html.erb
<h1>Editing grant</h1>

<%= render 'form' %>

<%= link_to 'Show', @grant %> |
<%= link_to 'Back', grants_path %>

app/views/grants/index.html.erb
<% @grants.each do |grant| %>
  <tr>
    <%= image_tag grant.image_url.to_s %>
    <td><%= grant.name %></td>
    <td><%= link_to 'Show', grant %></td>
    <td><%= link_to 'Edit', edit_grant_path(grant) %></td>
    <td><%= link_to 'Destroy', grant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grant', new_grant_path %>


<% @grants.each do |grant| %>
  <ul>
    <li><%= grant.name %></li>
      <ul>
        <% grant.tasks.each do |task| %>
          <li><%= task.name %></li>
        <% end %>
      </ul>
  </ul>
  
<% end %>


<%= link_to 'Add a New Grant', new_grant_path %>

app/views/grants/new.html.erb
<h1>New Grant</h1>

<%= render 'form' %>

app/views/grants/show.html.erb
<p>
  <b>Name:</b>
  <%= @grant.name %>
</p>

<p>
  <b>Private:</b>
  <%= @grant.private %>
</p>


<h4>Current Tasks:</h4>
 <ul class='dash-ul'>
   <% @grant.tasks.each do |task| %>
     <%= content_tag_for :li, task, class: 'dash-li' do %>
       <%= link_to task.name, task_path(task.id), class: 'dash-link' %>
       <p class="task-due"><%= if task.due then task.due.strftime("%m/%d/%Y") else "None" end %></p>
     <% end %>
   <% end %>
 </ul>


<%= link_to "Add Task", org_task_path(@grant.id) %> | <%= link_to "Return to Dashboard", dashboard_path %>