config/routes.rb
GrantTracker::Application.routes.draw do
 
  root :to => 'pages#index'
  get '/dashboard' => 'pages#dashboard', as: 'dashboard'
  
  get '/new/user' => 'organizations#new_user', as: 'org_user'
  get '/new/grant' => 'grants#new', as: 'org_grant'
  get '/new/:id/task' => 'tasks#new', as: 'org_task'
  
  get '/edit' => 'organizations#edit', as: 'edit_org'
  
  get '/signup' => 'organizations#new', as: 'signup'
  get '/organizations/:id/new_user' => 'organizations#new_user', as: 'organization_user'
  post '/users' => 'organizations#create_user'
  
  root :to => 'users#index'
  
  resources :user_sessions
  resources :users
  resources :tasks
  resources :grants
  resources :organizations, path: 'organization'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grant Tracker</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <link href='http://fonts.googleapis.com/css?family=Droid+Serif:400,700|Raleway:500' rel='stylesheet' type='text/css'>
  </head>
  <body>
   
    
   
   
<div id="container">

    <div id="inner">
     
      
        <div id="panel">
           
          <ul class ="menu">
            <% if current_user %>
            <li><%= link_to "Members", users_path %> </li>
            <li><%= link_to "Tasks", tasks_path %> </li>
            <li><%= link_to "Grants", grants_path %> </li>
            <li><%= link_to "Profile", user_path(current_user) %> </li>
           
             <% end %>
          </ul>
        </div> 
       
  <div id="home"> 
    
    <header>
        <nav>
          <ul>
            <% if current_user %>
              <li id="menu-button"> Menu </li>
              <li><%= link_to "Dashboard", dashboard_path %></li>
              <li><%= link_to "Logout", :logout, method: :post %></li>
            <% else %>
      
              
              <li id="signup"> <a href="#"> Signup </a> |</li>
              <li> <%= link_to "Login", :login %></li>
      
            <% end %>
          </ul>
        </nav>
      </header>
       <div class="main">
    
         
         
       
          <%= yield %>
        
        </div>
      
      </div>
    </div>
</div>



  </body>
</html>